# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lucas Rossdeutscher
tagline:             'Welcome to my website'
description:         'My personal website adapted and modified from a reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme originally made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://LRossdeutscher.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lucas Rossdeutscher
  url:               https://www.linkedIn.com/in/LRossdeutscher/
  email:             lucas.rossdeutscher@gmail.com

# Custom vars
version:             1.0.0
